version: '3'

services:
    mysql:
      image: mysql:8.0.36-debian
      container_name: mysql
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: root
 #     volumes:
 #       - ~/Documentos/curso_sql/mysql-data:var/lib/mysql
        
